### ISSUE TITLE
[Add/update member]

### ISSUE THREAD

**Issue by BennoKrojer** [McGill-NLP/mcgill-nlp.github.io#37] opened 2022-05-05 03:18 UTC
### Action

Update member

### Name

Benno Krojer

### Role

PhD

### Status

Current Member

### Bio

I work on language grounding and like Ultimate Frisbee

**Comment by xhlulu** [comment] 2022-05-05 03:20
Duplicate of #35

**Closed by xhlulu** 2022-05-05 03:20 UTC
Labels: automatic-add-update-member
